name: Build
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      # Configures gradle with caching
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      # Run "gradlew publish" for origin/dev and "gradlew build" for PRs or elsewhere
      - name: Execute Gradle ${{ (github.repository == 'PGMDev/Community' && github.ref == 'refs/heads/dev') && 'Publish' || 'Build' }}
        run: ./gradlew ${{ (github.repository == 'PGMDev/Community' && github.ref == 'refs/heads/dev') && 'publish' || 'build' }}
        env:
          GITHUB_TOKEN: ${{ (github.repository == 'PGMDev/Community' && github.ref == 'refs/heads/dev') && secrets.GITHUB_TOKEN || '' }}
      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: Community.jar
          path: build/libs/Community.jar
          if-no-files-found: error

